### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by tyilo** [fredagscafeen/web#4]
Freksen, 2017-05-17:

> Der blev til bestyrelsesmødet snakket om at vi gerne måtte informere om, at vi har haft åben hver fredag (i hvert fald siden så langt tilbage Boris kan huske).
> Man kunne måske også sige noget om historien og om hvilken slags bar vi er.
> Det at skrive teksten kunne fint uddelegeres til andre end Web.

**Comment by AndersSeverinsen** [comment]
Added a streak counter and some more info about the bar. Any updates can be added continuously.
